# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Michał Dziadkowiec – iOS Geek Developer & Apple Fan
email: michal@macdev.pl
address: Kraków, Poland
subtitle: >- # this means to ignore newlines until next key
  I gain my knowledge through self-education and I share my experiences with others.
description: >- # this means to ignore newlines until "baseurl:"
  On a daily basis, I create iOS applications and unusual internet applications together with my team of artisans.io. I also conduct original programming trainings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michal.dziadkowiec.pl" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
twitter_username: mdziadkowiec
github_username:  mdziadkowiec

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# header_pages:
  # - o-mnie.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
